import { ToastContainer } from "react-toastify";

import QueryClientProvider from "@/app/QueryClientProvider";

import "react-toastify/dist/ReactToastify.css";
import "@/styles/custom.css";
import "@/styles/global.css";
import "@/app/globals.css";
import "@/app/theme-config.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <main>{children}</main>
          <ToastContainer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
