import { ToastContainer } from "react-toastify";
import { redirect } from "next/navigation";

import { pageRedirect } from "@/actions/login";
import { auth } from "@/auth";

import "react-toastify/dist/ReactToastify.css";
import "@/styles/custom.css";
import "@/styles/global.css";
import "@/app/globals.css";
import "@/app/theme-config.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  if (session?.user?.type) {
    const redirectPath = pageRedirect(session?.user?.type!);
    redirect(redirectPath);
  }

  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        <ToastContainer />
      </body>
    </html>
  );
}
